### DISCUSSION TITLE
Prose class: first and last text element don't have 0 top en bottom margin respectively when using article block

### DISCUSSION THREAD

**Discussion by kobe-f8** [studio1902/statamic-peak#258] [Q&A] [answered]
I've noticed that a feature from the tailwind prose class isn't working as expected when using the article block. When you wrap some text in a div and apply the prose class, the first child loses it's top margin and the last text element loses it's bottom margin. But in peak the text you type is wrapped in a div inside the prose div, so the margin correction isn't applied.

Text inside div:
```
<!-- /components/_text.antlers.html -->
<div class="size-md">
    {{ text }}
</div>
<!-- End: /components/_text.antlers.html -->
```
![Screenshot 2022-09-13 at 10 09 02](https://user-images.githubusercontent.com/102222824/189847085-a0dad5da-cd9b-4e41-a0de-71d085c17936.png)

Text without being wrapped in a div
```
<!-- /components/_text.antlers.html -->
    {{ text }}
<!-- End: /components/_text.antlers.html -->
```
![Screenshot 2022-09-13 at 10 08 33](https://user-images.githubusercontent.com/102222824/189847107-ce6550a4-89e6-4cd4-bfc3-d2244c8fdbde.png)

As you can see when the text elements are directly inside the prose class, the margins are correct. 
Is there a way to keep the peak bard-set size classes `.size-md, .size-lg, .size-xl` by being wrapped in a div, but still have correct margins applied from the tailwind prose class.

**Comment by robdekort** [comment, marked as answer]
Good find. I think this should work:
```css
.prose :where(.prose > div > :first-child):not(:where([class~="not-prose"] *)) {
    margin-top: 0;
}
.prose :where(.prose > div > :last-child):not(:where([class~="not-prose"] *)) {
    margin-bottom: 0;
}
```
