### ISSUE TITLE
Combine global blueprints into a single tabbed "Settings" blueprint

### ISSUE THREAD

**Issue by pryley** [studio1902/statamic-peak#12]
Hope you don't mind me putting this here instead of making a pull request, still pushing through this deadline. 

![image](https://user-images.githubusercontent.com/134939/89675795-2849f280-d8b0-11ea-8fea-e418363e3656.png)

![image](https://user-images.githubusercontent.com/134939/89675841-3c8def80-d8b0-11ea-9903-ce004c26707f.png)

![image](https://user-images.githubusercontent.com/134939/89675891-4dd6fc00-d8b0-11ea-94cf-42ae091a5057.png)

```
sections:
  general:
    display: General
    fields:
      -
        handle: address
        field:
          type: textarea
          localizable: false
          listable: hidden
          display: Address
      -
        handle: business_hours
        field:
          input_type: text
          type: text
          localizable: false
          listable: hidden
          display: 'Business Hours'
      -
        handle: contact_sections
        field:
          sets:
            section:
              display: 'Contact Section'
              fields:
                -
                  import: contact_section
          type: replicator
          localizable: false
          listable: hidden
          display: 'Contact Sections'
  social_media:
    display: 'Social Media'
    fields:
      -
        handle: social_media
        field:
          sets:
            facebook:
              display: Facebook
              fields:
                -
                  import: social_media
            instagram:
              display: Instagram
              fields:
                -
                  import: social_media
            linkedin:
              display: LinkedIn
              fields:
                -
                  import: social_media
            twitter:
              display: Twitter
              fields:
                -
                  import: social_media
            vimeo:
              display: Vimeo
              fields:
                -
                  import: social_media
            youtube:
              display: YouTube
              fields:
                -
                  import: social_media
          type: replicator
          localizable: false
          listable: hidden
          display: 'Social Media'
  error_messages:
    display: 'Error Messages'
    fields:
      -
        handle: error_messages
        field:
          sets:
            error_301:
              display: 'Error 301'
              fields:
                -
                  import: error_message
            error_404:
              display: 'Error 404'
              fields:
                -
                  import: error_message
          type: replicator
          localizable: false
          listable: hidden
          display: 'Error Messages'

```
