### ISSUE TITLE
Basic SEO / Meta Tags / Site Setting Configuration

### ISSUE THREAD

**Issue by austriker27** [studio1902/statamic-peak#15]
Enhancement request: Basic SEO / Website Information
Probably best as a global config option. 

I suggest the following things be included:

## General
- Website Title
- Logo
- Favicon
- Touch Icon

## Meta Tags 
- Image
- Description
- Title

## Analytics
- Google Tag Manager ID
- Google Analytics ID
- Fathom Analytics ID

Here's a YAML file (for statamic V2) that I used in the past. Its just for inspiration and should be converted for V3. 

```
title: Default Globals
hide: true
sections:
  main:
    display: Main
    fields:
      site_name:
        type: text
        display: Website Name
        instructions: The name of your website
        localizable: true
      site_logo:
        type: assets
        display: Website Logo
        container: main
        folder: img
        restrict: true
        max_files: 1
        mode: grid
        width: 25
      website_favicon:
        container: main
        folder: img
        restrict: false
        max_files: 1
        mode: grid
        type: assets
        width: 25
        display: Website Favicon
      website_touch_icon:
        restrict: false
        type: assets
        width: 25
        display: Website Touch Icon
        container: main
        folder: img
        max_files: 1
        mode: grid
      global_meta_image:
        container: main
        folder: /
        restrict: false
        max_files: 1
        mode: grid
        type: assets
        width: 25
        display: Global Meta Image
      google_tag_manager_id:
        type: text
        width: 50
        display: Google Tag Manager ID
        instructions: 'Follows the pattern: GTM-XXXXXXX'
      google_analytics_id:
        type: text
        instructions: "If you're running GA through GTM leave this blank. Follows the pattern: UA-XXXXXXXXX-X"
        width: 50
        display: Google Analytics ID
      head_scripts:
        mode: table
        fields:
          description:
            type: text
            display: Description
          code:
            type: textarea
            display: Code
        type: grid
        instructions: 'Add meta tags and scripts to the `<head>` area of your site.'
        display: 'Head Scripts'
        add_row: Add Code
  footer:
    display: Footer
    fields:
      footer_scripts:
        mode: table
        fields:
          description:
            type: text
            display: Description
          code:
            type: textarea
            display: Code
        type: grid
        instructions: 'Add meta tags and scripts right before closing `</body>` area of your site.'
        display: 'Footer Scripts'
        add_row: Add Code
taxonomies: true
```

Also this site might be useful in creating the Meta Tags: http://heymeta.com
