### ISSUE TITLE
Vite 4.4.0 update → build error

### ISSUE THREAD

**Issue by delz-dev** [studio1902/statamic-peak#328]
### Bug description

```
vite v4.4.0 building for production...
✓ 9 modules transformed.
✓ built in 570ms
[vite:css] [postcss] postcss-import: /Users/patrick/web/test.ch/resources/css/custom.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
file: /Users/patrick/web/test.ch/resources/css/site.css:3:1
error during build:
CssSyntaxError: [postcss] postcss-import: /Users/patrick/web/test.ch/resources/css/custom.css:3:1: `@layer base` is used but no matching `@tailwind base` directive is present.
    at Input.error (/Users/patrick/web/test.ch/node_modules/postcss/lib/input.js:148:16)
    at AtRule.error (/Users/patrick/web/test.ch/node_modules/postcss/lib/node.js:60:32)
    at normalizeTailwindDirectives (/Users/patrick/web/test.ch/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)
    at /Users/patrick/web/test.ch/node_modules/tailwindcss/lib/processTailwindFeatures.js:30:98
    at plugins (/Users/patrick/web/test.ch/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/patrick/web/test.ch/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/patrick/web/test.ch/node_modules/postcss/lib/lazy-result.js:393:26)
    at async compileCSS (file:///Users/patrick/web/test.ch/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:38783:25)
    at async Object.load (file:///Users/patrick/web/test.ch/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:38735:32)
    at async Promise.all (index 0)
   ```

### How to reproduce

Update Vite from 4.3.9 to 4.4.0 …

### Environment

```yaml
Environment
Application Name: test
Laravel Version: 10.14.1
PHP Version: 8.2.7
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: test.ch.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.0 PRO
Statamic Addons
appswithlove/statamic-one-click-content-translation: 4.5.0
jonassiewertsen/statamic-livewire: 2.12.0
stillat/antlers-components: 2.0.0
studio1902/statamic-peak-browser-appearance: 2.0
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.6.2
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

nothing fancy …
