### ISSUE TITLE
Live preview error

### ISSUE THREAD

**Issue by mikemartin** [studio1902/statamic-peak#331]
### Bug description

Live preview is throwing this error when the document body is updated. 

```
site-9175988e.js?t=16893928703542:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_x_refs')
    at Yn.inline (site-9175988e.js?t=16893928703542:5:35404)
    at a (site-9175988e.js?t=16893928703542:5:2549)
    at site-9175988e.js?t=16893928703542:5:14653
    at Array.map (<anonymous>)
    at bn (site-9175988e.js?t=16893928703542:5:14623)
    at Object.la [as bind] (site-9175988e.js?t=16893928703542:5:14268)
    at Fs (site-9175988e.js?t=16893928703542:1:25461)
    at Function.<anonymous> (site-9175988e.js?t=16893928703542:1:22264)
    at i (site-9175988e.js?t=16893928703542:5:2202)
    at n (site-9175988e.js?t=16893928703542:5:2232)
```

I found the same error reported for Alpine here https://github.com/alpinejs/alpine/discussions/3003, where the solution was adding `x-data` to the element.

Sure enough, adding x-data to the <body> tag solves the issue.

    

### How to reproduce

- View entry in Live preview mode
- Edit content
- Live preview snippet throws error

### Environment

```yaml
Environment
Application Name: Coates Group
Laravel Version: 10.14.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: coatesgroup.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.2 PRO

Statamic Addons
rias/statamic-color-swatches: 2.2.0
studio1902/statamic-peak-browser-appearance: 3.1.1
studio1902/statamic-peak-commands: 2.1
studio1902/statamic-peak-seo: 2.6.1
studio1902/statamic-peak-tools: 3.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None
