### ISSUE TITLE
Unable to insert new lines in article's pull quote component

### ISSUE THREAD

**Issue by wojciechgabrys** [studio1902/statamic-peak#338]
### Bug description

**Problem**

The `Pull quote` set doesn't render new lines.

---

**What causes this:**

This is caused by the order of string modifiers in the [_pull_quote.antlers.html](https://github.com/studio1902/statamic-peak/blob/main/resources/views/components/_pull_quote.antlers.html#L20C76-L20C90) component.

```
Current order: {{ quote | nl2br | widont }}
```

> This order causes to insert `<br>` at the end of the line, and then `widont` triest to prevent `>` from wrapping into the following line by transforming `<br>` to `<br&nbsp;>`.

```
New order: {{ quote | widont | nl2br }}
```

> This order causes to insert `&nbsp;` first (to eliminate widowed characters), and then follows up with adding line breaks.

---

**PR solving this issue**
https://github.com/studio1902/statamic-peak/pull/339

---

### How to reproduce

1. Spin up a default Peak instance
2. Go to any `Article` set and add a `Pull quote` set inside
3. Enter a few lines of text
4. Save and view the result. The linebreaks will be missing:

![how-to-reproduce](https://github.com/studio1902/statamic-peak/assets/153263/55d4b400-a06d-4867-8111-f0f6ef9bd266)

### Logs

_N/A_

### Environment

```yaml
Environment
Application Name
Laravel Version: 10.19.0
PHP Version: 8.2.8
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: pullquotes.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Localization
Installed: cs, da, de, en, nl, nn
LaravelLang\Attributes\Plugin: v2.4.0
LaravelLang\HttpStatuses\Plugin: v3.4.2
LaravelLang\Lang\Plugin: 13.0.1
Protected Locales: en
Publisher Version: v14.7.0

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.2
studio1902/statamic-peak-commands: 2.3.3
studio1902/statamic-peak-seo: 5.0
studio1902/statamic-peak-tools: 3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

_N/A_
