### ISSUE TITLE
Multiple Checkboxes selected at once

### ISSUE THREAD

**Issue by stefankempf** [studio1902/statamic-peak#365]
### Bug description

I've installed a fresh clean peak install and I see the following issues with the form:

All checkbox entries get selected at once. Its not possible to only select one entry.

### How to reproduce

Install fresh peak starterkit and add basic form.

![CleanShot 2023-12-06 at 10 34 41](https://github.com/studio1902/statamic-peak/assets/20299885/4b55dfe5-9755-4585-8669-bbb7e6aec295)
![CleanShot 2023-12-06 at 10 34 25](https://github.com/studio1902/statamic-peak/assets/20299885/7c14f868-61d4-47ae-af89-766c959bca44)

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 10.35.0
PHP Version: 8.2.8
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: peak.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.38.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.2
studio1902/statamic-peak-commands: 3.1.0
studio1902/statamic-peak-seo: 7.3.1
studio1902/statamic-peak-tools: 4.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)
