### ISSUE TITLE
Forms with optional file not submittable

### ISSUE THREAD

**Issue by AndreasSchantl** [studio1902/statamic-peak#376]
### Bug description

It seems it's not possible to have optional files in forms. I couldn't yet narrow it down whether it is a Precognition issue or a Statamic issue itself. Can't get past [line 83 of the Form Controller](https://github.com/statamic/cms/blob/720d8a8de339f58d6a8e829fce9319ef2bfdf38c/src/Http/Controllers/FormController.php#L83)

### How to reproduce

Create a new peak site and add an asset field to the form (limit the max files to 1). 

Try submitting the form without the file (as it is optional) and see the error "Cannot upload files without encoding as multipart form data." coming up.

### Environment

```yaml
Environment
Application Name: Statamic Peak
Laravel Version: 10.39.0
PHP Version: 8.3.0
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: peak-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.42.1 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 4.0.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
