### ISSUE TITLE
image component using asset container on remote service: Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0

### ISSUE THREAD

**Issue by tomhayes** [studio1902/statamic-peak#381]
### Bug description

With Peak's image component when using an asset container on a remote service (DO Spaces in my instance), I get the error:

```
 Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0
``` 

I found this thread on the statamic-responsive-images github, which looks too similar to not be related: https://github.com/spatie/statamic-responsive-images/issues/166

### How to reproduce

Set up an asset container on remote service, use the image partial

### Environment

```yaml
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-livewire: 3.0.0
stillat/relationships: 2.1.3
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 4.1.0
studio1902/statamic-peak-seo: 8.0.0
studio1902/statamic-peak-tools: 4.2.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None
