### ISSUE TITLE
Error when cURL the packagist

### ISSUE THREAD

**Issue by buddy94** [studio1902/statamic-peak#382]
### Bug description

From one day to another peak stopped working.

In every reaquest that I do to my laravel application this is appended to the laravel logs:

This is the error:  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://repo.packagist.org/p2/studio1902/statamic-peak.json

If you go to this link: https://repo.packagist.org/p2/studio1902/statamic-peak.json it said: "404 not found, no packages here"

### How to reproduce

If you go to this link: https://repo.packagist.org/p2/studio1902/statamic-peak.json it said: "404 not found, no packages here"

### Environment

```yaml
Environment
Application Name: Amici Corecco
Laravel Version: 10.41.0
PHP Version: 8.2.10
Composer Version: 2.6.3
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: cookie

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 Solo
```
