### ISSUE TITLE
Favicon not showing in Bing search results when using browser appearance/favicons feature

### ISSUE THREAD

**Issue by simonfrost** [studio1902/statamic-peak#391]
### Bug description

Site favicon (svg) shows up in Google search results, but not in Bing.

Google:

<img width="757" alt="Screenshot 2024-05-31 at 09 33 12" src="https://github.com/studio1902/statamic-peak/assets/125280/64da227f-b8e9-44e3-9def-d380a3b5fbb9">

Bing:

<img width="865" alt="Screenshot 2024-05-31 at 09 33 29" src="https://github.com/studio1902/statamic-peak/assets/125280/c34ef4df-a77e-479f-9c14-bff4300f792b">

Seems to be set up correctly in the cp.

<img width="1003" alt="Screenshot 2024-05-31 at 09 34 47" src="https://github.com/studio1902/statamic-peak/assets/125280/6b58f40b-d58a-4272-9b38-67d08b6bf77f">

A bit of reading suggests that you need a link to the favicon in your sitemap.xml?

https://techcommunity.microsoft.com/t5/microsoft-bing/the-site-s-favicon-is-not-displayed-in-bing-search-results/m-p/3880129

Thanks!

### How to reproduce

Set up site, add favicon, push site live. Search for site in Google / Bing.

### Environment

```yaml
Environment
Application Name: Viva Esprit
Laravel Version: 9.52.15
PHP Version: 8.1.21
Composer Version: 2.4.2
Environment: production
Debug Mode: OFF
URL: vivaesprit.co.uk
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: half
Version: 4.48.0 PRO
```
