### ISSUE TITLE
Form Fieldtype "Files" errors "The Files Field must be an array" on sending

### ISSUE THREAD

**Issue by stefankempf** [studio1902/statamic-peak#396]
### Bug description

When I use a fields fieldtype inside my forms (either max files set to n or null), the form can't be send.

<img width="530" alt="Screenshot von 2024 08 26 um 17 41 49@2x" src="https://github.com/user-attachments/assets/9e34b597-8b72-421d-b4c7-d3533a182ff0">

I've tried on a fresh peak install with max files set to 1 or also null.

The error is similar to this issue: https://github.com/studio1902/statamic-peak/issues/366 only difference to the other issue: when I use the asset fieldtype, the error is not showing.

### How to reproduce

Use fresh peak install, add Files Field to existing form blueprint and try to send the form.

### Logs

```shell
storage/logs/laravel.log is empty 🤷‍♂️
```

### Environment

```yaml
Environment
Application Name: Peak
Laravel Version: 11.20.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.22.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.2
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 6.3.2
```
