### ISSUE TITLE
Composer could not authenticate with GitHub

### ISSUE THREAD

**Issue by fpolli** [studio1902/statamic-peak#401]
### Bug description

I tried to install Peak into existing Statamic and received the error message for a personal access token, so I went to Github, regenerated the token and followed the instructions from Peak:
composer config --global --auth github-oauth.github.com thelongasstokenstringoflettersand3454325432

There was no feedback.

I then went back to try and install the starter pack and got:

 ⠰ Preparing starter kit [studio1902/statamic-peak]...
The authenticity of host 'github.com (140.82.116.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
 ⠂ Preparing starter kit [studio1902/statamic-peak]...

After a long wait of a couple of minutes, this happens:

Composer could not authenticate with GitHub!
Please generate a personal access token at: https://github.com/settings/tokens/new
Then save your token for future use by running the following command:
Error installing starter kit [studio1902/statamic-peak].

### How to reproduce

Run this command from terminal:
sail artisan statamic:starter-kit:install studio1902/statamic-peak

### Environment

```yaml
using Laravel Sail 11, Lenovo laptop running Linux Mint 22. Terminal is bash
Environment
Application Name: Laravel
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.8.1
Environment: local
Debug Mode: ENABLED
URL: peak.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: database
Database: pgsql
Logs: stack / single
Mail: log
Queue: database
Session: database

Statamic
Addons: 0
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.34.0 Solo
```

### Additional details

I tried adding my token to composer.json but did not change the outcome
