### ISSUE TITLE
Consent embed Videos still shown after decline Consent

### ISSUE THREAD

**Issue by HannesEURESA** [studio1902/statamic-peak#407]
### Bug description

If i decline the consent for all Scripts and Embed Videos, the YouTube Videos still be displayed. 

### How to reproduce

Create embed Video in the config of the trackers like YouTube or TikTok.
Not accepting the cookies in the consent. 

### Environment

```yaml
Environment
Application Name: xxx
Laravel Version: 11.34.2
PHP Version: 8.3.4
Composer Version: 2.7.2
Environment: production
Debug Mode: ENABLED
URL: xxx
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: ses
Queue: database
Session: database

Livewire
Livewire: v3.5.15

Statamic
Addons: 8
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: half
Version: 5.41.0 PRO

Statamic Addons
jonassiewertsen/statamic-live-search: 2.1.1
jonassiewertsen/statamic-livewire: 3.8.1
rias/statamic-redirect: 3.8.2
statamic/eloquent-driver: 4.19.0
stillat/antlers-components: 2.4.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.5.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: file
Global Variables: file
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Additional details

Fresh statamic/statamic site via CLI
Statamic built with Vapor on AWS.
