### ISSUE TITLE
Tailwind Config File Missing on Fresh Install

### ISSUE THREAD

**Issue by thepalk** [studio1902/statamic-peak#409]
### Bug description

On a fresh install: Tailwind Config is not being copied into the install.

### How to reproduce

How to reproduce
	1.	Start with a fresh installation of the project.
	2.	Run the installation commands as per the documentation.
	3.	Check the project root for the tailwind.config.js file.

Expected behavior
The tailwind.config.js file should be automatically created or copied into the project root after installation.

Actual behavior
The tailwind.config.js file is missing.

### Environment

```yaml
Environment
Application Name: Designtag
Laravel Version: 11.36.1
PHP Version: 8.3.8
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: designtag.test
Maintenance Mode: OFF
Timezone: Europe/Berlin
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.43.0 PRO

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-commands: 8.13.0
studio1902/statamic-peak-seo: 8.18.0
studio1902/statamic-peak-tools: 6.6.0
```
