### ISSUE TITLE
Exception: Fieldset [statamic-peak-seo::seo_basic] not found

### ISSUE THREAD

**Issue by BenHMatrix** [studio1902/statamic-peak#415]
### Bug description

Created a new local Statamic site using Peak starter kit and when finished installing the front end and the CP of the new site throws this error `Fieldset [statamic-peak-seo::seo_basic] not found`

### How to reproduce

Install Statamic
`statamic new test-site`

Installation completes successfully. Go to new site in browser and error message returned.

```Statamic \ Exceptions \ FieldsetNotFoundException

Fieldset [statamic-peak-seo::seo_basic] not found

PHP 8.3.13 | 11.38.2
```

This is when visiting the front end and the CP, same error message.

As observed in other issues, there is no file at all referencing seo in /resources/fieldsets.

I've tried to set up new site several times using Peak Starter Kit and this happens each time.

Thanks in advance for any help you can provide.

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: Peak Test
Laravel Version: 11.38.2
PHP Version: 8.3.13
Composer Version: 2.8.4
Environment: local
Debug Mode: ENABLED
URL: peak-test.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.45.1 Solo

Statamic Addons
statamic/eloquent-driver: 4.19.1
studio1902/statamic-peak-browser-appearance: 3.6.0
studio1902/statamic-peak-seo: 8.19.0
studio1902/statamic-peak-tools: 6.6.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Sites: eloquent
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```
