### ISSUE TITLE
Missing form validation on large files

### ISSUE THREAD

**Issue by stefankempf** [studio1902/statamic-peak#423]
### Bug description

When my server has a php upload limit of lets say 5MB and I try to send a file larger than 5MB, the form validation for maximul filesize, e.g. `max_filesize:2000`, doesn't trigger. Instead, I get the following console error:

![Image](https://github.com/user-attachments/assets/5cc3c708-1464-4a62-8e20-fec91a3dbac3)

The form itself is showing no error message. Its unclear for the user, how to proceed and why the form hasn't been sent.

### How to reproduce

1. Set php upload limit to 5mb
2. Add form with the below field and validation
3. Try to upload a file larger than 5mb

```
handle: assets_field
field:
  container: files
  type: assets
  display: 'Assets Field'
  validate:
    - 'max_filesize:2000'
```

### Logs

```shell
–
```

### Environment

```yaml
Tested on a fresh install.

Environment
Application Name: Peak
Laravel Version: 12.0.1
PHP Version: 8.3.15
Composer Version: 2.8.5
Environment: local
Debug Mode: ENABLED
URL: peak.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.49.1 Solo

Statamic Addons
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.19.1
studio1902/statamic-peak-tools: 7.1.0
```
